# Generated by Django 5.1.4 on 2025-01-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
