# Generated by Django 5.1.4 on 2025-01-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tarefa_concluido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='task',
            new_name='tarefa',
        ),
    ]
