# Generated by Django 5.1.4 on 2025-01-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_task_tarefa_tarefa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='concluido',
            field=models.BooleanField(default=True),
        ),
    ]
