# Generated by Django 5.1.4 on 2025-01-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tarefa_concluido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
