# Generated by Django 5.1.4 on 2025-01-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_tarefa_concluido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='concluido',
            field=models.CharField(choices=[('True', 'Concluído'), ('False', 'Não Concluído')], default='False', max_length=10),
        ),
    ]
